version: '3.1'
services:
  subscriber:
    image: unsettling/dequeue:development
    build:
      context: ./src/Unsettling.Dequeue
      dockerfile: Dockerfile.development
    environment:
      - NETCOREAPP_ENVIRONMENT=Development
      - REMOTE_DEBUGGING
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15672
      - 5672