version: '3.1'
services:
  subscriber:
    image: unsettling/dequeue
    build:
      context: ./src/Unsettling.Dequeue
      dockerfile: Dockerfile
    environment:
      - NETCOREAPP_ENVIRONMENT=Production
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15672
      - 5672